apiVersion: krane.sh/v1
kind: CanaryPolicy
metadata:
  name: my-app
  namespace: krane
spec:
  base: aggregator-deployment
  virtualService: aggregator-vs
  service: aggregator-svc
  baselineMode: NEW
  ports:
  - port: 80
    name: default
    protocol: TCP
  test:
    image: gcr.io/petomalina/aggregator-testjob:v1
    boundary:
      requests: 60
  judge:
    image: busybox
    diffMetrics:
      - metric: container_cpu_system_seconds_total
        container: aggregator
        diff: 0.05