apiVersion: krane.sh/v1
kind: CanaryPolicy
metadata:
  name: my-app
  namespace: krane
spec:
  base: nginx-deployment
  virtualService: nginx-vs
  baselineMode: NEW
  ports:
  - port: 80
    name: default
    protocol: TCP
  test:
    image: gcr.io/petomalina/aggregator-testjob:v1
    boundary:
      requests: 10000
  judge:
    image: busybox