apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: aggregator-dr
  namespace: krane
spec:
  host: aggregator-svc
  subsets:
  - name: stable
    labels:
      krane.sh/tier: stable
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: aggregator-vs
  namespace: krane
spec:
  hosts:
  - '*'
  gateways:
  - krane-gw
  http:
    - match:
      - uri:
          prefix: "/"
      route:
      - destination:
          host: aggregator-svc
          subset: stable