apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-canary
  namespace: krane
  labels:
    app: nginx
    release: canary
    krane.sh/canary-policy: my-app
spec:
  selector:
    matchLabels:
      app: nginx
      release: canary
  template:
    metadata:
      labels:
        app: nginx
        release: canary
    spec:
      containers:
      - name: nginx
        image: tutum/hello-world
        ports:
        - containerPort: 80
