apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment-ah87p9-canary
  namespace: krane
  labels:
    app: aggregator
    version: canary-ah87p9
    krane.sh/tier: canary
    krane.sh/canary-policy: my-app
spec:
  selector:
    matchLabels:
      app: aggregator
      version: canary-ah87p9
      krane.sh/tier: canary
  template:
    metadata:
      labels:
        app: aggregator
        version: canary-ah87p9
        krane.sh/tier: canary
    spec:
      containers:
      - name: aggregator
        image: gcr.io/petomalina/aggregator:v4
        ports:
        - containerPort: 80
