// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/petomalina/krane/pkg/apis/krane/v1.Canary":             schema_pkg_apis_krane_v1_Canary(ref),
		"github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicy":       schema_pkg_apis_krane_v1_CanaryPolicy(ref),
		"github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicySpec":   schema_pkg_apis_krane_v1_CanaryPolicySpec(ref),
		"github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicyStatus": schema_pkg_apis_krane_v1_CanaryPolicyStatus(ref),
		"github.com/petomalina/krane/pkg/apis/krane/v1.CanarySpec":         schema_pkg_apis_krane_v1_CanarySpec(ref),
		"github.com/petomalina/krane/pkg/apis/krane/v1.CanaryStatus":       schema_pkg_apis_krane_v1_CanaryStatus(ref),
	}
}

func schema_pkg_apis_krane_v1_Canary(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Canary is the Schema for the canaries API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/petomalina/krane/pkg/apis/krane/v1.CanarySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/petomalina/krane/pkg/apis/krane/v1.CanaryStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/petomalina/krane/pkg/apis/krane/v1.CanarySpec", "github.com/petomalina/krane/pkg/apis/krane/v1.CanaryStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_krane_v1_CanaryPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryPolicy is the Schema for the canarypolicies API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicyStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicySpec", "github.com/petomalina/krane/pkg/apis/krane/v1.CanaryPolicyStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_krane_v1_CanaryPolicySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryPolicySpec defines the desired state of CanaryPolicy",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_krane_v1_CanaryPolicyStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryPolicyStatus defines the observed state of CanaryPolicy",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_krane_v1_CanarySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanarySpec defines the desired state of Canary",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_krane_v1_CanaryStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryStatus defines the observed state of Canary",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
