apiVersion: apps/v1
kind: Deployment
metadata:
  name: krane
spec:
  replicas: 1
  selector:
    matchLabels:
      name: krane
  template:
    metadata:
      labels:
        name: krane
    spec:
      serviceAccountName: krane
      containers:
        - name: krane
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - krane
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "krane"
