apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: krane
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - krane
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - krane.sh
  resources:
  - '*'
  - canarypolicies
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  - destinationrules
  verbs:
  - '*'
